set global tabstop 4
set global incsearch false
set global scrolloff 1,1
set global ui_options terminal_synchronized=true terminal_set_title=false terminal_assistant=none
set global startup_info_version 99991230

colorscheme gruvbox-dark
add-highlighter global/ show-matching
add-highlighter global/ number-lines -hlcursor -min-digits 4
add-highlighter global/ show-whitespaces -lf '' -indent '' -only-trailing
add-highlighter global/ wrap -word -indent
add-highlighter global/ column 80 default,black
add-highlighter global/ dynregex '%reg{/}' 0:black,yellow+F

# equivalent to expandtab in vim
# taken from https://github.com/mawww/kakoune/issues/1038#issuecomment-270643341
hook global InsertChar \t %{ exec -draft h@ }

# taken from https://github.com/mawww/kakoune/wiki/EditorConfig
hook global WinCreate ^[^*]+$ %{editorconfig-load}
