theme = "gruvbox_custom"

[editor]
continue-comments = false
completion-trigger-len = 1
completion-timeout = 5
rulers = [80, 100]
# idle-timeout = 800 # https://github.com/helix-editor/helix/discussions/8196#discussioncomment-9050882

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = [
  "spinner",
  "total-line-numbers",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "spacer",
  "spacer",
  "version-control",
]
center = [
  "register",
]
right = [
  "diagnostics",
  "spacer",
  # "version-control-changes",
  # "spacer",
  "spacer",
  "primary-selection-length",
  "selections",
  "spacer",
  "spacer",
  "position",
]

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

# [editor.lsp]
# display-inlay-hints = true

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"C-y" = "scroll_up"
"C-e" = "scroll_down"
"A-w" = "move_next_sub_word_start"
"A-b" = "move_prev_sub_word_start"
"A-e" = "move_next_sub_word_end"
"A-l" = "@*vnv"
"A-L" = "@*vNv"

[keys.insert]
"C-y" = "scroll_up"
"C-e" = "scroll_down"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"C-y" = "scroll_up"
"C-e" = "scroll_down"
"A-w" = "extend_next_sub_word_start"
"A-b" = "extend_prev_sub_word_start"
"A-e" = "extend_next_sub_word_end"
"A-l" = "@*n"
"A-L" = "@*N"

[keys.normal.space.x]
t = "@gslle\"tyeb\"iy] j\"iPa.sType = VK_STRUCTURE_TYPE<esc>\"tps[A-Z0-9]<ret>i_<esc>e<A-`>a;<esc>x=gh"
