theme = "gruvbox_dark_hard"

[editor]
rulers = [80]
completion-timeout = 5
completion-trigger-len = 1
auto-info = false

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = [
  "spacer",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "spacer", "spacer",
  "version-control",
]
right = [
  "diagnostics",
  "spacer", "spacer",
  "register",
  "primary-selection-length",
  "selections",
  "spacer", "spacer",
  "position",
  "total-line-numbers",
]

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.smart-tab]
enable = false

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
"A-w" = "move_next_sub_word_start"
"A-b" = "move_prev_sub_word_start"
"A-e" = "move_next_sub_word_end"

[keys.select]
"A-w" = "extend_next_sub_word_start"
"A-b" = "extend_prev_sub_word_start"
"A-e" = "extend_next_sub_word_end"
