[language-server.clangd]
args = ["-j=4", "--function-arg-placeholders=0", "--header-insertion=never"]
[[language]]
name = "c"
indent = { unit = "    ", tab-width = 4 }
formatter = { command = "clang-format", args = ["--style=file", "--fallback-style=none"] }
[[language]]
name = "cpp"
indent = { unit = "    ", tab-width = 4 }
formatter = { command = "clang-format", args = ["--style=file", "--fallback-style=none"] }
[[language]]
name = "nasm"
indent = { unit = "    ", tab-width = 4 }

# https://github.com/helix-editor/helix/issues/13501#issuecomment-2867283731
[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path=stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]
# https://pkg.go.dev/golang.org/x/tools/cmd/goimports
[[language]]
name = "go"
formatter = { command = "goimports" }

# https://github.com/razzmatazz/csharp-language-server
[[language]]
name = "c-sharp"
language-servers = ["csharp-ls"]

[[language]]
name = "cmake"
indent = { unit = "    ", tab-width = 4 }
[[language]]
name = "bash"
indent = { unit = "\t", tab-width = 4 }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser=html"] }
[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser=css"] }
[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser=typescript"] }
[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser=typescript"] }
[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser=typescript"] }
[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser=typescript"] }
