set-option -ga terminal-features *:rgb,*:usstyle
set-option -g copy-command wl-copy
set-option -g focus-events on
set-option -g set-titles on
set-option -g escape-time 0
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g status off
set-option -g main-pane-width 60%
set-option -g mouse on
set-option -g mode-keys vi
set-option -g status-keys emacs
set-option -g prefix C-Space
set-hook -g window-layout-changed 'select-layout main-vertical-mirrored'

bind-key -n C-w run-shell -C "split-window -b kak-dialog lf -C '#S'"
bind-key -n C-a run-shell -C "split-window -b kak-dialog fzf -C '#S'"
bind-key -n F7 display-popup -E -w80% -h80% tig status
bind-key -n F9 clear-history -Ht 2.1 \; respawn-pane -kt 2.1 gal build
bind-key -n F5 clear-history -Ht 2.1 \; respawn-pane -kt 2.1 gal debug
