set-option -ga terminal-features *:rgb,*:usstyle
set-option -g copy-command wl-copy
set-option -g focus-events on
set-option -g set-titles on
set-option -g display-time 0
set-option -g escape-time 0
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g status off
set-option -g mouse on
set-option -g mode-keys vi
set-option -g status-keys emacs
set-option -g prefix C-a

bind-key q display-panes -d0

# KEYBOARD:
#
# ` 1 2 3 4 5 6 7 8 9 0 - =
#    q w e r t y u i o p [ ] \
#    a s d f g h j k l ; '
#     z x c v b n m , . /
#
# FREE KEYS:
#
# `
#        e     y u           \
#    a       g h j k
#           v b

bind-key y split-window -bt1
bind-key g split-window -bt1 tig status
bind-key v run-shell -C "split-window -bt1 kak -C '#S'"
bind-key e run-shell -C "split-window -bt1 kak-dialog lf -C '#S'"
bind-key k run-shell -C "split-window -bt1 kak-dialog fzf -C '#S'"

bind-key -n F9 clear-history -Ht2.1 \; respawn-pane -kt2.1 gal build
bind-key -n F5 clear-history -Ht2.1 \; respawn-pane -kt2.1 gal debug
