theme = "gruvbox"

[editor]
line-number = "relative"
rulers = [80, 100]
auto-pairs = false
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
G = "goto_last_line"
g = { e = "no_op" }

[keys.select]
G = "goto_last_line"
g = { e = "no_op" }
