theme = "gruvbox"

[editor]
line-number = "relative"
rulers = [80, 100]
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
G = "goto_last_line"
g = { e = "no_op" }
"C-l" = ":redraw"
m = { g = { g = "@mi)s,<ret>r<ret>mi)<ret>ms<ret>" } }

[keys.select]
G = "goto_last_line"
g = { e = "no_op" }
"C-l" = ":redraw"
