theme = "gruvbox"

[editor]
line-number = "relative"
rulers = [80, 100]
completion-timeout = 50
completion-trigger-len = 1
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
G = "goto_last_line"
g = { e = "no_op" }

[keys.select]
G = "goto_last_line"
g = { e = "no_op" }
