theme = "gruvbox"

[editor]
line-number = "relative"
rulers = [80]
completion-timeout = 50
completion-trigger-len = 1
auto-info = false
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
